<div class="panel panel-default">
    
    <div class="panel-heading">
        <h3 class="panel-title">Contato</h3>
    </div>
    
    <div class="panel-body">        
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis necessitatibus molestias incidunt consequuntur unde commodi numquam, quibusdam sunt corrupti quos, aperiam culpa doloribus recusandae veritatis asperiores natus sint illum dignissimos?</p>   
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis necessitatibus molestias incidunt consequuntur unde commodi numquam, quibusdam sunt corrupti quos, aperiam culpa doloribus recusandae veritatis asperiores natus sint illum dignissimos?</p>   
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis necessitatibus molestias incidunt consequuntur unde commodi numquam, quibusdam sunt corrupti quos, aperiam culpa doloribus recusandae veritatis asperiores natus sint illum dignissimos?</p>   
    </div>
</div>
